2025-02-13T15:38:00 {"cpu": 0.1767578125, "cpu_total": 8, "cpu_usage": 0.0220947265625, "memory": 1835.0, "memory_total": 4840.0, "memory_usage": 0.37913223140495866, "pipeline_run_id": 64, "pipeline_schedule_id": 2, "pipeline_uuid": "datos_ventas", "hostname": "4dc745957cf6", "level": "INFO", "message": "Pipeline datos_ventas for run 64 in schedule 2 is alive.", "timestamp": 1739461080.538262, "uuid": "9d72ffb4122f4f8ea476a9eda17b830b"}
2025-02-13T15:38:00 {"cpu": 0.1767578125, "cpu_total": 8, "cpu_usage": 0.0220947265625, "memory": 1849.0, "memory_total": 4840.0, "memory_usage": 0.38202479338842976, "pipeline_run_id": 64, "pipeline_schedule_id": 2, "pipeline_uuid": "datos_ventas", "hostname": "4dc745957cf6", "level": "INFO", "message": "Pipeline datos_ventas for run 64 in schedule 2 is alive.", "timestamp": 1739461080.639954, "uuid": "2b95dccba19847c2bf71fd8fd8187b47"}
2025-02-13T15:38:00 {"block_run_id": 253, "block_uuid": "postgres_tables_creation", "pipeline_run_id": 64, "pipeline_schedule_id": 2, "pipeline_uuid": "datos_ventas", "hostname": "4dc745957cf6", "level": "INFO", "message": "Execute PipelineRun 64, BlockRun 253: pipeline datos_ventas block postgres_tables_creation", "timestamp": 1739461080.697717, "uuid": "a5f2b3b8a94f44048075f73fc08430e7"}
2025-02-13T15:38:00 {"block_run_id": 253, "block_uuid": "postgres_tables_creation", "pipeline_run_id": 64, "pipeline_schedule_id": 2, "pipeline_uuid": "datos_ventas", "hostname": "4dc745957cf6", "level": "INFO", "message": "BlockRun 253 (block_uuid: postgres_tables_creation) completes.", "timestamp": 1739461080.893974, "uuid": "398a4824205c49f8bdba5f1ce0e80e71"}
2025-02-13T15:38:10 {"cpu": 0.1748046875, "cpu_total": 8, "cpu_usage": 0.0218505859375, "memory": 1829.0, "memory_total": 4840.0, "memory_usage": 0.3778925619834711, "pipeline_run_id": 64, "pipeline_schedule_id": 2, "pipeline_uuid": "datos_ventas", "hostname": "4dc745957cf6", "level": "INFO", "message": "Pipeline datos_ventas for run 64 in schedule 2 is alive.", "timestamp": 1739461090.758764, "uuid": "01f4edfd715d4e4eaf9d6e232e9f69ec"}
2025-02-13T15:38:10 {"block_run_id": 254, "block_uuid": "postgres_data_insertion", "pipeline_run_id": 64, "pipeline_schedule_id": 2, "pipeline_uuid": "datos_ventas", "hostname": "4dc745957cf6", "level": "INFO", "message": "Execute PipelineRun 64, BlockRun 254: pipeline datos_ventas block postgres_data_insertion", "timestamp": 1739461090.925066, "uuid": "0c23c7ded3b74a0c9c7340e214295357"}
2025-02-13T15:38:11 {"block_run_id": 254, "block_uuid": "postgres_data_insertion", "pipeline_run_id": 64, "pipeline_schedule_id": 2, "pipeline_uuid": "datos_ventas", "hostname": "4dc745957cf6", "level": "INFO", "message": "BlockRun 254 (block_uuid: postgres_data_insertion) completes.", "timestamp": 1739461091.235585, "uuid": "14aa0ae310b849fdb42345249b29a8b9"}
2025-02-13T15:38:19 {"cpu": 0.1728515625, "cpu_total": 8, "cpu_usage": 0.0216064453125, "memory": 1832.0, "memory_total": 4840.0, "memory_usage": 0.3785123966942149, "pipeline_run_id": 64, "pipeline_schedule_id": 2, "pipeline_uuid": "datos_ventas", "hostname": "4dc745957cf6", "level": "INFO", "message": "Pipeline datos_ventas for run 64 in schedule 2 is alive.", "timestamp": 1739461099.702586, "uuid": "284f3bf5365e4d4e9adbee4ca2d60e3f"}
2025-02-13T15:38:19 {"block_run_id": 255, "block_uuid": "postgres_data_transformation", "pipeline_run_id": 64, "pipeline_schedule_id": 2, "pipeline_uuid": "datos_ventas", "hostname": "4dc745957cf6", "level": "INFO", "message": "Execute PipelineRun 64, BlockRun 255: pipeline datos_ventas block postgres_data_transformation", "timestamp": 1739461099.854886, "uuid": "16b5402ed72744f1995c2b2a2a086fbc"}
2025-02-13T15:38:20 {"block_run_id": 255, "block_uuid": "postgres_data_transformation", "pipeline_run_id": 64, "pipeline_schedule_id": 2, "pipeline_uuid": "datos_ventas", "hostname": "4dc745957cf6", "level": "EXCEPTION", "message": "BlockRun 255 (block_uuid: postgres_data_transformation) failed.", "timestamp": 1739461100.970383, "uuid": "37bc5609a03e4324a79ff06bb719231d", "error": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 647, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 621, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1154, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1691, in execute_sync\n    return __execute()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1668, in __execute\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1570, in __execute\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1910, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 2073, in _execute_block\n    outputs = self.execute_block_function(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 2169, in execute_block_function\n    output = block_function_updated(*input_vars, **global_vars)\n  File \"<string>\", line 27, in transform_sales_data\nTypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'\n", "error_stack": ["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1161, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1697, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1443, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 788, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 147, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 809, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 106, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 58, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1730, in schedule_all\n    PipelineScheduler(r).schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 159, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 333, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 640, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 20, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 121, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 198, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 351, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 315, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1235, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 682, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 159, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 464, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack()\n"], "error_stacktrace": "int() argument must be a string, a bytes-like object or a real number, not 'NoneType'"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 647, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 621, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1154, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1691, in execute_sync
    return __execute()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1668, in __execute
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1570, in __execute
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1910, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 2073, in _execute_block
    outputs = self.execute_block_function(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 2169, in execute_block_function
    output = block_function_updated(*input_vars, **global_vars)
  File "<string>", line 27, in transform_sales_data
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2025-02-13T15:38:29 {"cpu": 0.1708984375, "cpu_total": 8, "cpu_usage": 0.0213623046875, "memory": 1822.0, "memory_total": 4840.0, "memory_usage": 0.37644628099173555, "pipeline_run_id": 64, "pipeline_schedule_id": 2, "pipeline_uuid": "datos_ventas", "hostname": "4dc745957cf6", "level": "INFO", "message": "Pipeline datos_ventas for run 64 in schedule 2 is alive.", "timestamp": 1739461109.837506, "uuid": "48dc03cea62d426eb1a09ef0727ec89e"}
